---
- hosts: devmachines

  vars:

    vbox:
      guest_additions:
        version: '4.3.28'
        url: 'http://download.virtualbox.org/virtualbox/4.3.28/VBoxGuestAdditions_4.3.28.iso'

    lein:
      script:
        dest: ~/bin/lein
        checksum: "b59d741e3ad28b3a11ea28eab417133492ca2138"
        url:
          "https://raw.githubusercontent.com/technomancy/leiningen/2.5.1/bin/lein"
      standalone:
        dest: "~/.lein/self-installs/leiningen-2.5.1-standalone.jar"
        checksum: "1c526e6573713b0635a1f2d52502ffa04ae45383"

    vim:
      packages:
        - vim-X11
        - vim-enhanced
      plugins:
        #- faith/vim-go   keeps asking for github password
        - gmarik/Vundle.vim
        - godlygeek/tabular
        - guns/vim-clojure-static
        - itchyny/lightline.vim
        - kien/ctrlp.vim
        - mattn/emmet-vim
        - rking/ag.vim
        - scrooloose/nerdcommenter
        - tpope/vim-fireplace
        - tpope/vim-fugitive
        - tpope/vim-surround
        - Valloric/YouCompleteMe
        - vim-scripts/Solarized
        - vim-scripts/Tagbar

    utils:
      tmux:
        history_limit: 30000
        has_xsel: true
      dotfiles:
        - bashrc
        - gitconfig
        - tmux.conf
        - xinitrc

    keyboard:
      symbols_file: /usr/share/X11/xkb/symbols/us
      gnome_shell_input_sources: "[('xkb', 'us+dvorak')]"

  tasks:
  #- include: tasks/clojure.yaml
  - include: tasks/utils.yaml
  #- include: tasks/vim.yaml
  #- include: tasks/vbox.yaml
  - include: tasks/keyboard.yaml

# setup
  - name: dnf makecache
    command: dnf makecache
    changed_when: no

# util
  - name: install utility packages
    tags: util
    dnf: name={{item}} state=latest
    become: yes
    with_items:
      - ansible
      - docker
      - htop
      - mc
      - nmap
      - npm
      - pwsafe
      - tmux

# versioning
  - name: install versioning packages
    tags: versioning
    dnf: name={{item}} state=latest
    become: yes
    with_items:
      - git-svn
      - mercurial
      - tig

# python
  - name: install python packages
    tags: python
    dnf: name={{item}} state=latest
    become: yes
    with_items:
      - python-devel
      - python-ipython
      - python-virtualenv
      - python3-ipython
      - python3-virtualenv

# c
  - name: install c packages
    tags: c
    dnf: name={{item}} state=latest
    become: yes
    with_items:
      - clang
      - gcc
      - gcc-c++
      - kernel-devel

# go
  - name: install go packages
    tags: go
    dnf: name={{item}} state=latest
    become: yes
    with_items:
      - golang
