---
hosts:

  atom:
    groups: systemd_networkd
    vars:
      ansible_host: 192.168.7.1
      systemd_networkd_match:
        name: enp2s0
      systemd_networkd_addresses:
        - atom
        - ns1
        - dhcp1

  bismuth:
    groups: devmachine
    vars:
      ansible_host: 192.168.84.11

  carbon:
    groups:
      - devmachine
      - dnsserver
      - mount_nfs
      - systemd_networkd
    vars:
      ansible_host: 192.168.84.13
      dns_block_ads: yes
      gnome_shell: false
      systemd_networkd_match:
        name: enp0s3
      systemd_networkd_addresses:
        - carbon
      systemd_networkd_ips:
        - 192.168.123.123  # TODO: Is this used?
      mount_nfs_mounts:
        - device: iridium.alkali:/c/media
          dir: /mnt/iridium_media
          options:
            vers: vers=3
        - device: iridium.alkali:/c/archive
          dir: /mnt/iridium_archive
          options:
            vers: vers=3

  cerium:
    groups: devmachine
    vars:
      ansible_host: 192.168.84.12

  chrome:
    groups:
      - chromebook
      - workstation
    vars:
      ansible_connection: local  #?

  dhcp1:
    groups: dhcpserver
    vars:
      ansible_host: 192.168.1.31
      dhcp_network_interface: enp2s0
      dhcp_subnets:
        - network: 192.168.0.0
          netmask: 255.255.0.0
          ranges:
            - [192.168.135.1, 192.168.135.254]

  dhcp2:
    groups: dhcpserver
    vars:
      ansible_host: 192.168.1.32
      dhcp_network_interface: eth0

  git:
    groups: gitserver
    vars:
      ansible_host: 192.168.9.2

  helium:
    groups:
      - raspberrypi
      - systemd_networkd
      - webserver

    vars:
      ansible_host: 192.168.9.1
      systemd_networkd_match:
        name: eth0
      systemd_networkd_addresses:
        - helium
        - git
        - ns2
        - dhcp2
        - pxe
        - media

  iridium:
    groups: readynas

  media:
    groups: mediaserver
    vars:
      ansible_host: 192.168.71.1
      mediaserver_folders:
        - /var/media/Music
        - /var/media/Videos
        - /var/media/Pictures
        - /mnt/icybox/media/Music
        - /mnt/icybox/media/Videos
        - /mnt/icybox/media/Pictures

  ns1:
    groups: dnsserver
    vars:
      ansible_host: 192.168.1.11
      dns_block_ads: yes

  ns2:
    groups: dnsserver
    vars:
      ansible_host: 192.168.1.12
      dns_block_ads: yes

  pxe:
    groups: pxeserver
    vars:
      ansible_host: 192.168.1.121

  sodium:
    groups: devmachine
    vars:
      ansible_host: 192.168.84.3
...
