---
dependencies:
  chromebook: [workstation]
  devmachine: [workstation]

hosts:

  atom:
    groups: systemd_networkd

  bismuth:
    groups: devmachine

  carbon:
    groups:
      - systemd_networkd
      - devmachine
      - dnsserver
      - mount_nfs

  cerium:
    groups: devmachine

  chrome:
    groups:
      - chromebook
      - workstation

  dhcp1:
    groups: dhcpserver

  dhcp2:
    groups: dhcpserver

  git:
    groups: gitserver

  helium:
    groups:
      - systemd_networkd
      - raspberrypi
      - webserver

  iridium:
    groups: readynas

  media:
    groups: mediaserver

  ns1:
    groups: dnsserver

  ns2:
    groups: dnsserver

  pxe:
    groups: pxeserver

  sodium:
    groups: devmachine
...
