---
- hosts: systemd_networkd
  become: yes
  roles:
    - systemd-networkd

- hosts: mount_nfs
  become: yes
  roles:
    - mount-nfs

- hosts: dhcpserver
  roles:
    - dhcpserver

- hosts: dnsserver
  roles:
    - dns

- hosts: pxeserver
  roles:
    - pxeserver

- hosts: workstation
  roles:
    - common

- hosts: devmachine
  roles:
    - development

- hosts: webserver
  roles:
    - webserver

- hosts: gitserver
  roles:
    - gitserver

- hosts: mediaserver
  roles:
    - mediaserver
