---
- hosts: dhcpservers
  roles:
    - dhcpserver

- hosts: dnsservers
  roles:
    - dns

- hosts: workstations
  roles:
    - common

- hosts: devmachines
  roles:
    - development

- hosts: gitservers
  roles:
    - gitserver

- hosts: mediaservers
  roles:
    - mediaserver
