---
- hosts: systemd_networkd
  become: yes
  roles:
    - systemd-networkd

- hosts: mount_nfs
  become: yes
  roles:
    - mount-nfs

- hosts: dhcpservers
  roles:
    - dhcpserver

- hosts: dnsservers
  roles:
    - dns

- hosts: pxeservers
  roles:
    - pxeserver

- hosts: workstations
  roles:
    - common

- hosts: devmachines
  roles:
    - development

- hosts: webservers
  roles:
    - webserver

- hosts: gitservers
  roles:
    - gitserver

- hosts: mediaservers
  roles:
    - mediaserver
