---
- hosts: dnsservers
  roles:
    - dns
- hosts: vboxguests
  roles:
    - vboxguest

- hosts: workstations
  roles:
    - common

- hosts: devmachines
  roles:
    - development

- hosts: gitservers
  roles:
    - gitserver
