---
- name: install tftp
  pacman:
    name: tftp-hpa
    state: present
  become: yes

- name: create directory
  file:
    dest: /var/pxe
    state: directory
  become: yes

- name: download netboot image
  get_url:
    url: https://www.archlinux.org/static/netboot/ipxe.8da38b4a9310.pxe
    dest: /var/pxe/pxelinux.0
  become: yes

- name: tftpd.service
  template:
    dest: /usr/lib/systemd/system/tftpd.service
    src: tftpd.service
  become: yes
  notify: restart tftpd
