---
- file: path=~/dotfiles state=directory mode=0755
  tags: utils

- name: stuff
  tags: [utils]
  template: src="templates/{{item}}" dest="~/dotfiles/{{item}}"
  register: "{{item}}_template"
  with_items: utils.dotfiles

- name: list links in ~
  changed_when: false
  tags: [utils]
  command: find -maxdepth 1 -type l -print
  register: dotlinks

  # ansible refuses to overwrite file with link, maybe there's a -f option
- name: remove non links
  tags: [utils]
  file: dest=~/.{{item}} state=absent
  when: item not in dotlinks.stdout
  with_items: utils.dotfiles

- name: link files to ~
  file: src=~/dotfiles/{{item}} dest=~/.{{item}} state=link
  tags: [utils]
  with_items: utils.dotfiles
