---
- name: install dhcpd
  pacman:
    name: dhcp
    state: present
  become: yes

- name: dhcpd.conf
  tags: dhcp
  template:
    dest: /etc/dhcpd.conf
    src: dhcpd.conf
  become: yes
  notify: restart dhcpd

- name: dhcpd.service
  tags: dhcp
  template:
    dest: "/etc/systemd/system/dhcpd4@{{ dhcp_network_interface }}.service"
    src: dhcpd.service
  become: yes
  notify: restart dhcpd
