set gfn=Liberation\ Mono\ 10
set guioptions-=m "-=mT doesn't work?
set guioptions-=T
set lines=60
{% if vim_default_colorscheme is defined %}
  set background=dark
  colorscheme {{ vim_default_colorscheme }}
{% endif %}
