scriptencoding utf-8
set encoding=utf-8

set nocompatible
filetype off

" performance
set lazyredraw
{% if chromebook is not defined %}
  set ttyfast
{% endif %}

{% if 'gmarik/Vundle.vim' in vim_plugins_github %}
  " vundle
  set rtp+=~/.vim/bundle/Vundle.vim
  call vundle#begin()
  {% for plugin in vim_plugins_github %}
    Plugin '{{ plugin }}'
  {% endfor %}
  call vundle#end()
{% else %}
  set rtp+=
  {% for plugin in vim_plugins_github %}
    \~/.vim/bundle/{{ plugin|regex_replace('.*/', '') }},
  {% endfor %}
  {% for plugin in vim_plugins_github %}
    \~/.vim/bundle/{{ plugin|regex_replace('.*/', '') }}/after,
  {% endfor %}
{% endif %}

" mappings
let mapleader = ' '
"  powerline
set laststatus=2

"  searching
set hlsearch
set incsearch
set showmatch
set smartcase

{% if 'Valloric/YouCompleteMe' in vim_plugins_github %}
  " turn down ycm logging
  let g:ycm_server_log_level = 'warning'
{% endif %}

filetype plugin indent on

" indentation and such
set nu
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set smarttab
set autoindent
set nosmartindent
set ruler

set autowrite
set autoread

set hidden
set wildignore=*/build/*,*/.svn/*,*/.git/*,*.class,*.zip
set wildignore+=*/__pycache__/*,*.egg,*.pyc,*.pyo,*.o,*/bin/*
set wildmenu
set foldmethod=indent
set foldlevelstart=20

syntax on
syntax enable

" remaps
{% if chromebook is defined %}
  " <C-v> closes chrome tab
  nnoremap <C-v> <C-w>
{% endif %}

nnoremap <C-k> 10k
nnoremap <C-j> 10j
nnoremap <esc> :
nnoremap <up> :so %<CR>
nnoremap <down> :!./%<CR>
nnoremap <left> :bn<CR>
nnoremap <right> :bp<CR>
nnoremap <leader>i :set list!<CR>
nnoremap <leader>p :set paste!<CR>
nnoremap <leader>t :TagbarToggle<cr>

" replace
nnoremap <leader>riw yiw:/gc<home>%s/\<<C-r>"\>/
nnoremap <leader>riW yiW:/gc<home>%s/\<<C-r>"\>/

{% if 'rking.ag.vim' in vim_plugins_github %}
  " search
  nnoremap <leader>a :Ag 
{% endif %}

vnoremap <leader>n :normal 

" swap
set directory=~/.vim/tmp
set backupdir=~/.vim/tmp

" plugins
{% if 'tpope/vim-fugitive' in vim_plugins_github %}
  nnoremap <leader>gb :Gblame<cr>
  nnoremap <leader>gc :Gcommit<cr>
  nnoremap <leader>gd :Gdiff<cr>
  nnoremap <leader>ge :Gedit<cr>
  nnoremap <leader>gs :Gstatus<cr>
{% endif %}

{% if stat_fzf_vim.stat.exists %}
  let fzf_wrap={
    \ 'source': join(["find",
    {% for find_arg in vim_fzf_find_args %}
      \ "{{find_arg}}",
    {% endfor %}
    \]),
    \ 'options': [
    \   '--color', 'dark',
    \   '--expect', 'ctrl-v,ctrl-x,ctrl-t',
    \   '--no-mouse',
    \   '--prompt', '> ',
    \ ]
    \ }

  nnoremap <C-p> :call fzf#run(fzf#wrap(fzf_wrap))<cr>
{% endif %}

" ctags
set tags=./tags;$HOME

" autocommands
au VimResized * exe "normal! \<c-w>="

autocmd BufRead,BufNewFile *.html,*.js,*.css,*.scss,*.yaml,*.yml,*.groovy
    \ setl shiftwidth=2 tabstop=2 softtabstop=2

autocmd BufRead,BufNewFile *.yaml,*.yml
    \ setl indentkeys-=<:>

autocmd BufRead,BufNewFile *.groovy
    \ setl noet

" cosmetics

" highlight lines that are 80+ chars
call matchadd('ColorColumn', '\%80v', 20)

if $TERM =~ '256'
  set t_Co=256
  set background=dark
  {% if vim_default_colorscheme is defined %}
    colorscheme {{ vim_default_colorscheme }}
  {% endif %}
endif

{% if 'itchyny/lightline.vim' in vim_plugins_github %}
  let g:lightline = {
    \ 'separator': {'left':'', 'right':''},
    \ 'subseparator': {'left':'', 'right':'⁕'}}
  set listchars=tab:▸⋅,eol:¬,trail:⋅
{% endif %}
