
---
- name: dnf update
  tags: [vbox]
  dnf: name=* state=latest
  become: yes
  register: dnf_update

- name: restart machine
  tags: [vbox]
  shell: bash -c "sleep 1; shutdown -r now" &
  async: 0
  poll: 0
  become: yes
  when: dnf_update.changed

- name: waiting for server to come back
  tags: [vbox]
  local_action: wait_for host={{ inventory_hostname }}
                port=22
                delay=15
                timeout=300
                connect_timeout=40
                state=started
  when: dnf_update.changed

- name: install build dependencies
  tags: [vbox]
  dnf: name={{item}} state=latest
  become: yes
  register: dnf_build_deps
  with_items:
    - gcc
    - kernel
    - kernel-devel
    - kernel-headers
    - dkms
    - make
    - bzip2
    - perl

- name: restart machine
  tags: [vbox]
  shell: bash -c "sleep 1; shutdown -r now" &
  async: 0
  poll: 0
  become: yes
  when: dnf_build_deps.changed

- name: waiting for server to come back
  tags: [vbox]
  when: dnf_build_deps.changed
  local_action: wait_for host={{ inventory_hostname }}
                port=22
                delay=15
                timeout=300
                connect_timeout=40
                state=started

- name: make temp folder for guest additions iso
  command: mktemp -d
  register: iso_dir
  tags: [vbox]

- set_fact:
    guest_addions_dest="{{iso_dir.stdout + '/' + vbox.guest_additions.url.rsplit('/',1)[1]}}"
  tags: [vbox]

- name: download guest additions
  get_url: dest="{{guest_addions_dest}}"
           url="{{vbox.guest_additions.url}}"
  tags: [vbox]
  register: guest_additions_downloaded
  become: yes

- name: make temp folder for mounting iso
  command: mktemp -d
  register: mnt_dir
  tags: [vbox]

- name: mount iso
  command: mount -t iso9660 -o loop {{guest_addions_dest}} {{mnt_dir.stdout}}
  become: yes
  tags: [vbox]

- name: install vbox additions
  tags: [vbox]
  command: "{{mnt_dir.stdout + '/' + 'VBoxLinuxAdditions.run'}}"
  become: yes
  # always returns 1 :(
  ignore_errors: yes

- name: unmount iso
  command: umount {{mnt_dir.stdout}}
  become: yes
  tags: [vbox]

- name: restart machine
  tags: [vbox]
  shell: bash -c "sleep 1; shutdown -r now" &
  async: 0
  poll: 0
  become: yes

- name: waiting for server to come back
  tags: [vbox]
  local_action: wait_for host={{ inventory_hostname }}
                port=22
                delay=15
                timeout=300
                connect_timeout=40
                state=started
